feat : avatar added
sach10-create/Nova-ui-Component-Library pull request #1
Opened 2022-02-02 14:10 UTC by sach10-create

Avatar added into the component library.

2022-02-02 20:05 UTC, sonishreyas reviewed
Looks good to me

2022-02-02 20:05 UTC, sonishreyas commented on components/avatar/avatar.html
> +    <!-- <link rel="stylesheet" href="../../css/components.css" /> -->
This can be removed

2022-02-03 01:15 UTC, itsmebipul00 commented on components/avatar/avatar.html
> +                    <li class="component">Alerts</li>
You could instead wrap the a tag inside the li tag

2022-02-03 01:19 UTC, itsmebipul00 commented
Great work btw!!

2022-02-03 03:34 UTC, iRohitGaur commented on components/avatar/src/css/profile-avatar.css
> +    padding: 0 0.5rem 0 0.5rem;
try to give in px to values less than 10px

2022-02-03 03:35 UTC, iRohitGaur commented on components/avatar/src/css/simple-avatar.css
> +  /* align-items: center; */
remove commented code

2022-02-03 03:37 UTC, iRohitGaur commented on css/root-style.css
> +    --shadow-color: #9ca3af;
suggestion: keep variable names in uppercase for better visibility

2022-02-03 03:37 UTC, iRohitGaur approved these changes
Good to merge with changes 👍🏻

2022-02-03 04:52 UTC, zoef-yt requested changes
There are a lot of commented code make sure you remove it

2022-02-03 04:52 UTC, zoef-yt commented on css/badge-icon.css
> +  box-shadow: 0.5rem 0.5rem 0.5rem var(--shadow-color);
use px here

2022-02-03 04:52 UTC, zoef-yt commented on css/code-tabs.css
> +  /* background: #00b2b2; */
remove commented code.

2022-02-03 04:52 UTC, zoef-yt commented on css/profile-avatar.css
> +  padding: 0 0.5rem 0 0.5rem;
use px for rem less than 1rem

2022-02-03 04:52 UTC, zoef-yt commented on css/root-style.css
> +    /* --primary-color-light : #4F7777; */
removed the commented code if not in use.

2022-02-03 04:52 UTC, zoef-yt commented on css/simple-avatar.css
>  /* @import url(../../../../css/root-style.css); */
remove commented code

2022-02-03 08:33 UTC, merged