feat: added grids
sach10-create/Nova-ui-Component-Library pull request #13
Opened 2022-02-19 19:02 UTC by sach10-create

2022-02-19 21:53 UTC, sumitk-singh commented on css/grid-3.css
> +  font-weight: normal;
font-weight :normal is default value, it can be remove from here.

2022-02-19 21:54 UTC, sumitk-singh commented on css/grid-3.css
> +  border: 2px solid black;
use color variable

2022-02-19 21:56 UTC, sumitk-singh requested changes
rest of the code looks clean, good to merger on the changes.

2022-02-20 05:11 UTC, sonishreyas approved these changes
Looks good to merge

2022-02-20 05:14 UTC, merged